# Generated by Django 5.2 on 2025-06-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='link_interativo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
    ]
