# Generated by Django 5.2 on 2025-06-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL),
        ),
    ]
