# Generated by Django 4.2.23 on 2025-08-01 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_merge_20250707_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='criador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarioforum',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_forum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='usuarios.aula'),
        ),
        migrations.AlterField(
            model_name='respostaforum',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_forum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostaquiz',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_quiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostaquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='usuarios.quiz'),
        ),
    ]
