# Generated by Django 5.2.4 on 2025-08-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_quiz_pdf_alter_aula_arquivo_alter_quiz_criador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='usuarios.quiz'),
            preserve_default=False,
        ),
    ]
