# Generated by Django 4.2.24 on 2025-11-10 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_aula_tipo_conteudo_alter_aula_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioforum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respostaforum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='respostas_curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
