# Generated by Django 5.2 on 2025-06-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_entrega_options_rename_data_postagem_aula_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostaquiz',
            old_name='enviado_em',
            new_name='respondido_em',
        ),
        migrations.AddField(
            model_name='respostaquiz',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respostaquiz',
            name='resposta',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='usuarios.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='usuarios.questao')),
            ],
        ),
    ]
