# Generated by Django 5.2 on 2025-06-29 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_enviado_em_respostaquiz_respondido_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('pontos', models.PositiveIntegerField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='atividades/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
