# Generated by Django 5.2 on 2025-06-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_desempenho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenho',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
