# Generated by Django 4.2.23 on 2025-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_quiz_criador_alter_comentarioforum_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='agendada',
            field=models.BooleanField(default=False),
        ),
    ]
