# Generated by Django 5.2 on 2025-04-21 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_postagem', models.DateField()),
                ('agendada', models.BooleanField(default=False)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('link_reuniao', models.URLField(blank=True)),
                ('slide', models.FileField(blank=True, null=True, upload_to='slides/')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
