# Generated by Django 5.2 on 2025-06-28 01:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_quiz_arquivo_quiz_link_interativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={},
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='data_postagem',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='link_reuniao',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='data_agendada',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='slide',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='link_interativo',
        ),
        migrations.AddField(
            model_name='aula',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='aulas/'),
        ),
        migrations.AddField(
            model_name='aula',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2025, 6, 28, 1, 47, 18, 519259, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.CreateModel(
            name='RespostaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.quiz')),
            ],
        ),
    ]
