# Generated by Django 5.2 on 2025-07-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_desempenho_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='enviado_em',
            new_name='data_envio',
        ),
        migrations.AddField(
            model_name='entrega',
            name='resposta_texto',
            field=models.TextField(blank=True),
        ),
    ]
