# Generated by Django 5.2 on 2025-07-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_solicitacaoprofessor_senha'),
        ('usuarios', '0017_create_superuser'),
    ]

    operations = [
    ]
