# Generated by Django 4.2.24 on 2025-09-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_entrega_comentario_entrega_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of user consent to terms.', null=True),
        ),
    ]
