# Generated by Django 5.2.4 on 2025-08-05 15:54

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_aula_agendada'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/pdf/', validators=[usuarios.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='aula',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='aulas/', validators=[usuarios.models.validate_video]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
