# Generated by Django 4.2.24 on 2025-11-03 00:54

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_usuario_consent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='tipo_conteudo',
            field=models.CharField(choices=[('video_url', 'Link de Vídeo Externo'), ('video_upload', 'Upload de Vídeo'), ('pdf', 'Documento PDF'), ('undefined', 'Indefinido')], default='undefined', help_text='Define se a aula é um link, um vídeo ou um PDF.', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Use para uploads de .mp4, .mov ou .pdf', null=True, upload_to='aulas_uploads/', validators=[usuarios.models.validate_aula_arquivo]),
        ),
        migrations.AlterField(
            model_name='aula',
            name='video_url',
            field=models.URLField(blank=True, help_text="Use para links do YouTube, Vimeo, etc. (se tipo_conteudo='video_url')"),
        ),
    ]
